//
//  UPDRSData.swift
//  AI4PDDemo
//
//  Created by Tim_Feige on 17.12.24.
//

import Foundation

struct UPDRSData {
    private init() {}
    
    static let instance = UPDRSData()
    
    static let ViewModelUPDRSItems: [UPDRSItem] = [
        UPDRSItem(orderNumber: 0,
                  date: nil,
                  itemName: UPDRSItemName.RestingTremor.rawValue,
                  displayName: "Ruhetremor",
                  recordingPosition: .sitting,
                  instructionTest: "Versuchen Sie nun einfach entspannt zu sitzen und von einhundert in siebener Schritten herunterzuzählen.",
                  side: .none,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: false,
                  recordingDuration: 5),
        UPDRSItem(orderNumber: 1,
                  date: nil,
                  itemName: UPDRSItemName.MovementTremor.rawValue,
                  displayName: "Bewegungstremor rechts",
                  recordingPosition: .sitting,
                  instructionTest: "Wir beginnen zunächst mit dem rechten Arm. Strecken Sie zunächst Ihren Arm mit ausgestrecktem Zeigefinger weit nach vorn und führen Sie anschließend den Zeigefinger an Ihre Nasenspitze. Danach strecken Sie den Arm wieder weit aus. Wiederholen Sie das bitte fünf mal.",
                  side: .right,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: false,
                  recordingDuration: 6
                 ),
        UPDRSItem(orderNumber: 2,
                  date: nil,
                  itemName: UPDRSItemName.MovementTremor.rawValue,
                  displayName: "Bewegungstremor links",
                  recordingPosition: .sitting,
                  instructionTest: "Bitte führen Sie die Übung nun genau so mit dem linken Arm aus.",
                  side: .left,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: false,
                  recordingDuration: 6
                 ),
        UPDRSItem(orderNumber: 3,
                  date: nil,
                  itemName: UPDRSItemName.Fingertap.rawValue,
                  displayName: "Finger Tippen rechts",
                  recordingPosition: .sitting,
                  instructionTest: "Wir beginnen zunächst mit der rechten Hand. Berühren Sie mit Ihrem rechten Zeigefinger die Kuppe Ihres Daumens. Öffnen Sie nun beide Finger soweit wie möglich von einander und führen Sie anschließend die Fingerkuppen wieder zusammen. Wiederholen Sie das nun bitte zehn mal und versuchen Sie bitte die Bewegung so schnell wie möglich und mit der größtmöglichen Amplitude auszuführen.",
                  side: .right,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: true,
                  recordingDuration: 4),
        UPDRSItem(orderNumber: 4,
                  date: nil,
                  itemName: UPDRSItemName.Fingertap.rawValue,
                  displayName: "Finger Tippen links",
                  recordingPosition: .sitting,
                  instructionTest: "Bitte führen Sie das Finger Tippen nun genau so mit der linken Hand aus.",
                  side: .left,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: false,
                  recordingDuration: 4),
        UPDRSItem(orderNumber: 5,
                  date: nil,
                  itemName: UPDRSItemName.PronationSupination.rawValue,
                  displayName: "Pronation und Supination rechts",
                  recordingPosition: .sitting,
                  instructionTest: "Strecken Sie den rechten Arm vor Ihrem Körper mit der Handfläche nach unten aus. Wenden Sie nun Ihre Handfläche mit größtmöglicher Amplitude alternierend zehn Mal nach oben und nach unten",
                  side: .right,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: false,
                  recordingDuration: 5),
        UPDRSItem(orderNumber: 6,
                  date: nil,
                  itemName: UPDRSItemName.PronationSupination.rawValue,
                  displayName: "Pronation und Supination links",
                  recordingPosition: .sitting,
                  instructionTest: "Bitte führen Sie die Übung nun genau so mit dem linken Arm aus.",
                  side: .left,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: false,
                  recordingDuration: 5),
        UPDRSItem(orderNumber: 7,
                  date: nil,
                  itemName: UPDRSItemName.ToeTapping.rawValue,
                  displayName: "Fußtippen rechts",
                  recordingPosition: .sitting,
                  instructionTest: "Setzen Sie sich dafür bitte möglichst aufrecht hin. Stellen Sie Ihre Füße so auf den Boden, dass sie eine Bequeme Position für ihre Ferse einnehmen. Nun Tippen Sie bitte mit den Zehen wieder zehn mal und mit größtmöglicher Amplitude und schnellstmöglich auf den Boden. Wir beginnen wieder mit dem rechten Fuß.",
                  side: .right,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: true,
                  recordingDuration: 5),
        UPDRSItem(orderNumber: 8,
                  date: nil,
                  itemName: UPDRSItemName.ToeTapping.rawValue,
                  displayName: "Fußtippen Links",
                  recordingPosition: .sitting,
                  instructionTest: "Bitte führen Sie die gleiche Übung nun einmal mit ihrem linken Fuß aus.",
                  side: .left,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: false,
                  recordingDuration: 5),
        UPDRSItem(orderNumber: 9,
                  date: nil,
                  itemName: UPDRSItemName.Walking.rawValue,
                  displayName: "Gehen",
                  recordingPosition: .standing,
                  instructionTest: "Laufen Sie auf die Kamera zu, solange Sie vollständig im Bild sind. Drehen Sie sich dann einmal um einhunderachtzig Grad und laufen wieder zurück.",
                  side: .none,
                  url: nil,
                  rating: nil,
                  showInstructionByDefult: false,
                  recordingDuration: 12
                 )
    ]
    
}
